"""
Jarvis AI Assistant — Database & Memory Management
===================================================
Handles conversation persistence. Automatically connects to Supabase if configured;
otherwise falls back to a local SQLite database (jarvis.db) so it always works.
"""

import logging
import sqlite3
import os
from typing import Any, dict, list
from config import config

logger = logging.getLogger("jarvis.database")

# SQLite Database path (used if Supabase is not configured)
SQLITE_DB_PATH = os.path.join(os.path.dirname(__file__), "jarvis.db")

# Supabase SQL schema for reference:
# 
# create table if not exists public.jarvis_memory (
#     id bigint generated by default as identity primary key,
#     created_at timestamp with time zone default timezone('utc'::text, now()) not null,
#     role text not null,
#     content text not null,
#     session_id text default 'default'::text not null
# );
#
# create index if not exists jarvis_memory_session_id_idx on public.jarvis_memory (session_id);

_supabase_client = None

def get_supabase_client():
    """Lazy initialize the Supabase client."""
    global _supabase_client
    if _supabase_client is not None:
        return _supabase_client
    
    if not config.supabase_url or not config.supabase_key:
        return None
        
    try:
        from supabase import create_client, Client
        _supabase_client = create_client(config.supabase_url, config.supabase_key)
        return _supabase_client
    except Exception as exc:
        logger.error("Failed to initialize Supabase client: %s", exc)
        return None

def init_db() -> None:
    """Initialize the database tables."""
    client = get_supabase_client()
    if client:
        logger.info("⚡ Supabase database configured. Verifying memory table...")
        try:
            # Test query to verify if table exists
            client.table("jarvis_memory").select("id").limit(1).execute()
            logger.info("✅ Supabase memory table is ready!")
        except Exception as exc:
            logger.warning(
                "⚠️ Could not access 'jarvis_memory' table in Supabase. "
                "Make sure you run the SQL schema in your Supabase SQL Editor:\n\n"
                "CREATE TABLE public.jarvis_memory (\n"
                "    id bigint generated by default as identity primary key,\n"
                "    created_at timestamp with time zone default timezone('utc'::text, now()) not null,\n"
                "    role text not null,\n"
                "    content text not null,\n"
                "    session_id text default 'default'::text not null\n"
                ");\n"
                "CREATE INDEX jarvis_memory_session_id_idx ON public.jarvis_memory (session_id);\n"
            )
    else:
        logger.info("💾 No Supabase credentials. Initializing local SQLite database...")
        try:
            conn = sqlite3.connect(SQLITE_DB_PATH)
            cursor = conn.cursor()
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS jarvis_memory (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    role TEXT NOT NULL,
                    content TEXT NOT NULL,
                    session_id TEXT DEFAULT 'default' NOT NULL
                )
            """)
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_session ON jarvis_memory (session_id)")
            conn.commit()
            conn.close()
            logger.info("✅ Local SQLite database is ready!")
        except Exception as exc:
            logger.error("Failed to initialize SQLite database: %s", exc)

def save_message(role: str, content: str, session_id: str = "default") -> None:
    """Save a chat message to the active database (Supabase or SQLite)."""
    # Don't save binary base64 screenshots directly to database to avoid bloat
    if isinstance(content, list):
        # Clean history items to keep only text for storage
        text_parts = [part["text"] for part in content if part.get("type") == "text"]
        content_str = "\n".join(text_parts)
    else:
        content_str = str(content)

    client = get_supabase_client()
    if client:
        try:
            client.table("jarvis_memory").insert({
                "role": role,
                "content": content_str,
                "session_id": session_id
            }).execute()
        except Exception as exc:
            logger.error("Failed to save message to Supabase: %s", exc)
            # Fallback to local SQLite if Supabase write fails
            _save_sqlite(role, content_str, session_id)
    else:
        _save_sqlite(role, content_str, session_id)

def _save_sqlite(role: str, content_str: str, session_id: str) -> None:
    try:
        conn = sqlite3.connect(SQLITE_DB_PATH)
        cursor = conn.cursor()
        cursor.execute(
            "INSERT INTO jarvis_memory (role, content, session_id) VALUES (?, ?, ?)",
            (role, content_str, session_id)
        )
        conn.commit()
        conn.close()
    except Exception as exc:
        logger.error("Failed to save message to SQLite: %s", exc)

def load_messages(session_id: str = "default", limit: int = 50) -> list[dict[str, Any]]:
    """Load last messages from the active database."""
    client = get_supabase_client()
    if client:
        try:
            response = client.table("jarvis_memory") \
                .select("role, content") \
                .eq("session_id", session_id) \
                .order("created_at", desc=False) \
                .limit(limit) \
                .execute()
            # Return list of {role, content}
            return [{"role": row["role"], "content": row["content"]} for row in response.data]
        except Exception as exc:
            logger.error("Failed to load messages from Supabase: %s", exc)
            return _load_sqlite(session_id, limit)
    else:
        return _load_sqlite(session_id, limit)

def _load_sqlite(session_id: str, limit: int) -> list[dict[str, Any]]:
    try:
        conn = sqlite3.connect(SQLITE_DB_PATH)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        # Fetch the latest N messages in ascending order
        cursor.execute(
            "SELECT role, content FROM (SELECT role, content, id FROM jarvis_memory WHERE session_id = ? ORDER BY id DESC LIMIT ?) ORDER BY id ASC",
            (session_id, limit)
        )
        rows = cursor.fetchall()
        conn.close()
        return [{"role": row["role"], "content": row["content"]} for row in rows]
    except Exception as exc:
        logger.error("Failed to load messages from SQLite: %s", exc)
        return []
